### PR TITLE
fix react-dom dep

### PR DESCRIPTION
**Pull request by JRJurman**
react-dom dependency needed for newer version of react

### CODE REVIEW

**Comment by bbesmanoff** [comment]
:+1:

-----Original Message-----

**Comment by JRJurman** [comment]
@bbesmanoff do you know why the circle-ci build is still failing? there's no other peers, but it's still spitting out 

`peerinvalid The package react@0.14.0-rc1 does not satisfy its siblings' peerDependencies requirements!`

**Comment by bbesmanoff** [comment]
Try rebuilding without cache.  Ill look in to why it is still caching dependencies

-----Original Message-----

**Comment by JRJurman** [comment]
@bbesmanoff you're a legend

**Pull request merged**
