### PR TITLE
Graph doesnt rerender

### LINKED ISSUE #72: Graph does not re-render
1. Visit `/stocks`
2. Type any stock (i.e. `GOOG`) and press submit
3. Type any other stock (i.e. `AMZN`)

Expected: Graph updates to the second stock
Actual: Graph does not update

### PR DESCRIPTION
**Pull request by bbesmanoff**
Closes #72

### CODE REVIEW

**Comment by JRJurman** [comment]
I'm getting peer dependency issues running npm-install on this branch

**Comment by bbesmanoff** [comment]
@JRJurman: try clearing your `node_modules` folder and see if that works.  If not, please post what modules are causing the error

**Comment by JRJurman** [comment]
@bbesmanoff: thanks, that worked!

**Comment by JRJurman** [comment]
:+1:

**Comment by bbesmanoff** [comment]
This should have auto-closed...

**Pull request closed without merging**
